### ISSUE TITLE
Support for _gcl_au cookie

### ISSUE THREAD

**Issue by IO101010** [MichaelBreitung/mibreit-cookie-consent#1]
Hi,

I see on https://www.mibreit-photo.com that the cookies beginning with _ga are handled by setting cookieName = "GA4_Active" (or "GA4") in the javascript code.

This doesn't handle _gcl_au cookies which my website uses. I've tried improvising values like "GCL_Active" and "_gcl_au" but my guesses aren't having an affect. Are these cookies supported?

Thanks!

**Comment by MichaelBreitung** [comment]
Hi,

The cookie consent bar itself, does not have any functionality connected to GA4 or other code in Google Tag manager. The naming of the cookies in the cookie bar configuration is completely separate from that.

I have three videos. In the second and third video, I show how to use the cookies you set with the cookie consent bar together with Tag Manager to control the functionality of external scripts like GA4.

Here's an article with the tutorial videos: http://www.michael-breitung.com/blog/cookie-consent-with-google-tag-manager-and-google-analytics-4/

The concept can also be applied to other external scripts you might use. The cookie bar is just for setting cookies that you define. You then have to use that information / those cookies to control functionality of your website you want to have optional. In my examples it's GA4 via Google tag manager.

I hope this helps.

cheers,

 Michael

**Comment by MichaelBreitung** [comment]
Here's a blog with some videos on how to use: http://www.michael-breitung.com/blog/cookie-consent-with-google-tag-manager-and-google-analytics-4/
